### dhcp-server values.yaml 
# - DHCP server in kubernetes allows for the defaining of DHCP pools and settings via yaml 
# - Streamlining the way you deploy and manage a DHCP pool

# DHCP currently only supports running 1 rpelica as they both will overwrite eachothers leases on the PVC
# In the future this can be fixed with a primary/secondary if you can bind a static IP to the pods
replicas: 1 

# For changing the default image for the DHCP Server
image:
  repository: dhcp-server-k8s
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}
podLabels: {}

resources: 
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

# If you need to specify a node to run the dhcp server on Specifiy here
nodeSelector: {}

# Any node tollerations
tolerations: []

# Specifying any affinitys
affinity: {}


securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

# By default we run as fsgroup 2000 
# To enable the backup job to function as intended when mounting the PVC
podSecurityContext:
  # fsGroup: 1000

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

pvc:
  enabled: true
  storageClassName: ""
  storage: 1Gi

backup:
  enabled: false
  schedule: "0 2 * * *"
  image:
    repository: dhcp-server-k8s
    tag: latest
    pullPolicy: IfNotPresent
  restartPolicy: OnFailure
  s3:
    endpoint: ""
    accessKey: ""
    secretKey: ""
    bucketName: ""
    path: ""


# Global includes all common DHCP configuration such as lease time and options 
global:
  defaultLeaseTime: "600"
  maxLeaseTime: "7200"
  option: []
    # - name: domain-name
    #   value: "vm.lootbot.cloud"
    # - name: domain-name-servers
    #   value: "192.168.1.1"
  extra: ""

# Subnet: a DHCP subnet block defined by the ip CIDR you want DHCP to lisen on
#   - a subnet needs to be finded for every ip range an interface has, 
#   - EX (ens-192) has an ip address 192.168.1.100, you would need to define the 
#     subnet 192.168.1.0/24 so DHCP can lisen and respond on that interface
subnet:
  - name: default
    cidr: "192.168.1.0"
    netmask: "255.255.255.0"
    # DHCP allows for changing lease times per subnet
    defaultLeaseTime: "600"
    maxLeaseTime: "7200"
    # DHCP allows for defineing multible ranges inside a subnet block
    range: 
      # First is the first IP DHCP will issue a lease for
      # Last is the last IP DHCP will issue a lease for
      - first: "192.168.1.20"
        last: "192.168.1.254"
    option:
    # DHCP options can be defined per pool or globaly 
    # All subnets will inhearate the default global options
    # if any options here are set the entire list will be overwritten
      - name: domain-name-servers
        value: "192.168.1.1"
      - name: routers
        value: "192.168.1.1"
      - name: broadcast-address
        value: "192.168.1.255"
    # Extra allows for the addation of addational DHCP fields not concidered by the chart
    # EX: adding primary/secondary servers
    extra: ""