---
# Source: dhcp-k8s/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: dhcp-k8s
  labels:
    helm.sh/chart: dhcp-k8s-1.0.0
    app.kubernetes.io/name: dhcp-k8s
    app.kubernetes.io/instance: dhcp-k8s
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true
---
# Source: dhcp-k8s/templates/secrets.yaml
# The secret will include all S3 Configuration
apiVersion: v1
kind: Secret
metadata:
  name: dhcp-k8s-s3
type: Opaque
data:
  S3_ACCESS_KEY: dGVzdA==
  S3_SECRET_KEY: dGVzdA==
  S3_BUCKET: ZGhjcC1zZXJ2ZXItYmFja3Vwcw==
  S3_ENDPOINT: dGVzdC5jb20=
  S3_PATH: ZGhjcC1zZXJ2ZXI=
---
# Source: dhcp-k8s/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: dhcp-k8s-primary
  namespace: default
data:
  dhcpd.conf: |

    # Global Configuration
    option domain-name vm.lootbot.cloud;
    option domain-name-servers 192.168.1.1;
    default-lease-time 600;
    max-lease-time 7200;
    authoritative;
    update-conflict-detection true;
    # Subnet example-1
    subnet 192.168.1.0 netmask 255.255.255.0 {
      range 192.168.1.20 192.168.1.254;
      option domain-name-servers 192.168.1.1;
      option routers 192.168.1.1;
      option broadcast-address 192.168.1.255;
      default-lease-time 600;
      max-lease-time 7200;
    }
    # Subnet kubernetes
    subnet 10.42.0.16 netmask 255.255.255.0 {
    }
---
# Source: dhcp-k8s/templates/pvc.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dhcp-k8s-primary
  labels:
    dhcp-server/role: primary
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 5Gi
---
# Source: dhcp-k8s/templates/primary.yaml
# Primary DHCP Server
## Runs as a deployment mounting the PVC for leaases and config generated by this chart
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dhcp-k8s-primary
  labels:
    helm.sh/chart: dhcp-k8s-1.0.0
    app.kubernetes.io/name: dhcp-k8s
    app.kubernetes.io/instance: dhcp-k8s
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
    dhcp-server/role: primary
spec:
  replicas: 1 # Static define the num of replicas untill leader election is implemented
  selector:
    matchLabels:
      app.kubernetes.io/name: dhcp-k8s
      app.kubernetes.io/instance: dhcp-k8s
      dhcp-server/role: primary
  template:
    metadata:
      labels:
        dhcp-server/role: primary
        helm.sh/chart: dhcp-k8s-1.0.0
        app.kubernetes.io/name: dhcp-k8s
        app.kubernetes.io/instance: dhcp-k8s
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      # Mounting a service account wont do anything right now,
      # In the future it will make it posible to do leader election via lease objects 
      # Also allow us to write the DHCPD logs as kubernetes events
      serviceAccountName: dhcp-k8s
      securityContext:
        fsGroup: 1000
      # TODO Make the container not use HostNetwork 
      # Or make it so it can be diefined in the values.yaml
      hostNetwork: true
      containers:
        # Define the Primary DHCP Server instance
        - name: dhcp-server
          # The image can be overwritten by the values.yaml
          image: "dhcp-server-k8s:1.0.0"
          imagePullPolicy: IfNotPresent  
          # The secruity context might need to be privliged
          securityContext:
            {}
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
          # The ports for the container are static at 67 for DHCP requests
          # The DHCP sevrer will reply on 68 UDP but its outbound traffic
          ports:
            - name: dhcp
              containerPort: 67
              protocol: UDP
          # the resources for the container are set via the values.yaml
          # for the envioments that need requests/limits defined
          # this is where we will be either mounting the PVC or nounting the EMPTYDIR
          # Also mounting the config map that contains the dhcpd config
          volumeMounts:
            - name: leases
              mountPath: /dhcpd/leases/
            - name: config
              mountPath: /dhcpd/config/
      volumes:
        - name: leases
          persistentVolumeClaim:
            claimName: dhcp-k8s-primary
        - name: config
          configMap:
            name: dhcp-k8s-primary
---
# Source: dhcp-k8s/templates/backup.yaml
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dhcp-k8s-primary-backup
  labels:
    helm.sh/chart: dhcp-k8s-1.0.0
    app.kubernetes.io/name: dhcp-k8s
    app.kubernetes.io/instance: dhcp-k8s
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: "Forbid"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          affinity:
            podAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
              - labelSelector:
                  matchLabels:
                    dhcp-server/role: primary
                topologyKey: "kubernetes.io/hostname"
          securityContext:
            fsGroup: 1000
          containers:
          - name: backup
            image: "dhcp-server-k8s:latest"
            imagePullPolicy: IfNotPresent
            securityContext:
              {}
            envFrom:
            - secretRef:
                name: dhcp-k8s-s3
            volumeMounts:
            - name: leases
              mountPath: /dhcpd/leases
              readOnly: true
            - name: config
              mountPath: /dhcpd/config
              readOnly: true
            resources:
              requests:
                cpu: "100m"
                memory: "256Mi"
              limits:
                cpu: "200m"
                memory: "512Mi"
          restartPolicy: OnFailure
          volumes:
          - name: leases
            persistentVolumeClaim:
              claimName: dhcp-k8s-primary
          - name: config
            configMap:
              name: dhcp-k8s-primary
