# The secret will include all S3 Configuration
{{- if .Values.backup.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "dhcp-k8s.fullname" . }}-s3
type: Opaque
data:
  S3_ACCESS_KEY: {{ .Values.backup.s3.accessKey | b64enc }}
  S3_SECRET_KEY: {{ .Values.backup.s3.secretKey | b64enc }}
  S3_BUCKET: {{ .Values.backup.s3.bucketName | b64enc }}
  S3_ENDPOINT: {{ .Values.backup.s3.endpoint | b64enc }}
  S3_PATH: {{ .Values.backup.s3.path | b64enc }}
{{- end }}
